### PR TITLE
 Helmet cams

### PR DESCRIPTION
**Pull request by RemieRichards**
* These helmet cams update to show who is wearing them (otherwise "No User")
* Replaced attach_cam with canAttachCam
* Moved canAttachCam to /helmet (only helmets have camera code so why put this on /head?)
* Added removing helmet cams
* Added attaching helmet cams
* Attaching/Removing helmet cams retains the upgrades of a camera (X-ray, etc.)
* Reworks helmet update_icon(), Helmet cams now require an icon_state on the helmet. <B>(No icon states are provided!!)</B> (Feel free to revert this one bullet point)
* Places the auto creation of a helmet camera behind a spawnWithHelmetCam variable, defaulting to off

### CODE REVIEW

**Comment by Dorsisdwarf** [comment]
Helmet cams should probbably be an overlay instead of an icon_state, so you can have 1 camera for any helmets you want to add it to.

**Comment by RemieRichards** [comment]
@Dorsisdwarf I did that originally but adapted it for the Steelpoint-Remie merge since honestly helmet overlays on the actual worn mob icon are stupid difficult (may ACTUALLY be impossible in this current state?)

**Comment by Steelpoint** [comment]
Overlays are nice but if I do that on top of seclites then things suddenly spiral out of control.

**Comment by Steelpoint** [comment]
Now I'm the Collaborator

**Comment by RemieRichards** [comment]
Hehe, Cute.

**Pull request merged**
